### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by papb** [Polyconseil/pylint-strict-informational#2]
I am using `pylint 2.9.3`, the exit code is still zero.

**Comment by papb** [comment]
[Workaround](https://github.com/PyCQA/pylint/issues/3363#issuecomment-880420939):

```bash
find .venv/lib -path '*/pylint/constants.py' -exec sed -r -i -e 's@(^MSG_TYPES_STATUS = .*):\s*0,(.*)@\1: 4,\2  # monkey-patched, waiting for pylint#3363@g' {} ';'
```

**Comment by MarkCBell** [comment]
The reason that this no longer works is commit https://github.com/PyCQA/pylint/commit/ab094aef2504d9603b8332607298242db8968335. This changed the default behaviour of pylint so that a run will automatically be marked as succeeding if its score is >= `config.fail_under` (where as previously it only required `score > config.fail_under`). 

Since informational alerts do not affect the score, runs with (only) them finish with a perfect 10.0 / 10.0 score and so this shortcut is applied and an `exit(0)` is immediately triggered. You can prevent this shortcut from triggering by also setting the `fail_under` value to be something larger than 10, for example by adding `--fail-under=11` to your usage of pylint.

**Comment by xavfernandez** [comment]
`--fail-on=useless-suppression` should also work (if you've got a precise list of interesting Informational code)

**Comment by papb** [comment]
I ended up [solving my problem](https://github.com/PyCQA/pylint/issues/3363#issuecomment-1247492172) by updating pylint and adding the following to my `.pylintrc` (without need for this package):

> evaluation=10.0 - ((float(5 * error + warning + refactor + convention + info) / statement) * 10)
